version: "3"

services:
  backend:
    build: .
    command: yarn run dev
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app/backend
    environment:
      NETWORK: Milena
      SERVER: Local
      NODE_ENV: development
