version: "3"

services:
  backend:
    build: .
    command: yarn start
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app/backend
    environment:
      NETWORK: Milena
      SERVER: Local
