version: "3.8"

networks:
  milena-network-test:
    driver: bridge

secrets:
  sign_private_key:
    file: ../secrets/sign_private_key.secret
  sign_public_key:
    file: ../secrets/sign_public_key.secret
  mysql_password:
    file: ../secrets/mysql_password.secret
  mailgun_apikey:
    file: ../secrets/mailgun_apikey.secret

services:
  redis_test:
    image: "redis:6.0"
    container_name: milena_redis_test
    expose:
      - "6379"
    networks:
      - milena-network-test

  mysql_test:
    image: mysql:8
    container_name: milena_mysql_test
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: milena_test
    secrets:
      - mysql_password
    networks:
      - milena-network-test

  backend_test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    image: milena_backend:test
    container_name: milena_backend_test
    command: yarn run run-jest
    expose:
      - "4000"
    depends_on:
      - redis_test
      - mysql_test
    volumes:
      - ..:/usr/app/backend
    environment:
      NETWORK: Milena
      SERVER: Test
      NODE_ENV: development
      MYSQL_DATABASE: milena_test
      MYSQL_HOST: mysql_test
      REDIS_HOST: redis_test
    secrets:
      - sign_private_key
      - sign_public_key
      - mysql_password
      - mailgun_apikey
    networks:
      - milena-network-test
