version: "3.8"

volumes:
  milena_storage:
    driver: local

networks:
  milena-network:
    driver: bridge

secrets:
  sign_private_key:
    file: ../secrets/sign_private_key.secret
  sign_public_key:
    file: ../secrets/sign_public_key.secret
  mysql_password:
    file: ../secrets/mysql_password.secret
  mailgun_apikey:
    file: ../secrets/mailgun_apikey.secret

services:
  redis:
    image: "redis:6.0"
    container_name: milena_redis_dev
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - milena-network

  mysql:
    image: mysql:8
    container_name: milena_mysql_dev
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - milena_storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: milena_dev
    secrets:
      - mysql_password
    networks:
      - milena-network

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: milena_backend:dev
    container_name: milena_backend_dev
    command: yarn run dev
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - mysql
    restart: on-failure
    volumes:
      - ..:/usr/app/backend
    environment:
      NETWORK: Milena
      SERVER: Local
      NODE_ENV: production
      MYSQL_DATABASE: milena_dev
      MYSQL_HOST: mysql
      REDIS_HOST: redis
    secrets:
      - sign_private_key
      - sign_public_key
      - mysql_password
      - mailgun_apikey
    networks:
      - milena-network
